### ISSUE TITLE
Geocode Restaurant Inspection Data

### ISSUE THREAD

**Issue by jasonasher** [jasonasher/dc_doh_hackathon#13]
Start with the DC DOH Food Service Establishment Inspection report data in the `/Data Sets/Restaurant Inspections/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

Write a script to geocode each inspection (using the establishment address data in the inspection summary file).

**Input:**
CSV files with inspection summary and violation details

**Output:**
A CSV file with

- 1 row for each inspection id
- The dataset should include the following columns:

`inspection_id`: The ID for the inspection
`latitude`: The latitude of the establishment address of the inspection
`longitude`: The latitude of the establishment address of the inspection

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)
Let Jason or Elizabeth know so they can make sure the results are widely available as other issues depend upon this step.

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by jasonasher** [comment]
Start with the DC DOH Food Service Establishment Inspection report data in the `/Data Sets/Restaurant Inspections/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

1. Geocode each inspection (using the establishment address data in the inspection summary file)
2. Add additional columns to each inspection that denote
    a. Whether or not the inspection resulted in closure
    b. Whether or not the inspection violations observed included rodents or trash

TODO: feature ideas
- New complaints
- Overdue inspections (uses risk category)
- Inspections that find rodent or trash violations
- Inspections that result in closure
- Number of establishments by type and risk category

**Input:**
CSV files with inspection summary and violation details

**Output:**

1. A CSV file that maps food establishment addresses
A CSV file with

- 1 row for each building permit type and subtype, and each week, year, and census block
- The dataset should include the following columns:

`feature_id`: The ID for the feature, in this case, TODO
`feature_type`: TODO
`feature_subtype`: TODO
`year`: The ISO-8601 year of the feature value
`week`: The ISO-8601 week number of the feature value
`census_block_2010`: The 2010 Census Block of the feature value
`value`: The value of the feature, i.e. TODO

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by dardinel** [comment]
Jason, looks like I will be late tomorrow but I went ahead and did the geocodes on this since your notes said other things were dependent on it.  I put the output file, the R code used to create it, and a sample plot of points dropped on a map into your dropbox.  Hope this helps.

- Greg

**Comment by jasonasher** [comment]
This is great - thank you, especially for doing it so early!
