### ISSUE TITLE
Extract 'New Complaints' Feature from Restaurant Inspection Data

### ISSUE THREAD

**Issue by jasonasher** [jasonasher/dc_doh_hackathon#16]
Start with the DC DOH Food Service Establishment Inspection report data in the `/Data Sets/Restaurant Inspections/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

Note that this depends upon the geocoding results from Issue #13

**Input:**
CSV files with inspection summary and violation details

**Output:**
A CSV file with

- 1 row for each establishment type and risk category, and each week, year, and census block
- The following columns:

`feature_id`: The ID for the feature, in this case, "restaurant_inspection_complaints"
`feature_type`: The `establishment_type` from the restaurant set
`feature_subtype`: The `risk_category` from `1`-`5`
`year`: The ISO-8601 year of the feature value
`week`: The ISO-8601 week number of the feature value
`census_block_2010`: The 2010 Census Block of the feature value
`value`: The value of the feature, i.e. the number of new complaints for establishments with the given types and risk categories in the specified week, year, and census block.

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by brycecf** [comment]
Is anyone else working on this?

**Comment by jasonasher** [comment]
@brycecf Yes, Xavier Gutierrez is - see our sign up sheet's 'Tasks for Day-Of' tab. You could try to find and work with him?

**Comment by jasonasher** [comment]
Checked at hacknight. Note that these are counting new inspections of complaints, technically, and not 'new complaints' (as we don't have the date of the original complaint. We may want to aggregate these by rolling week.
