### ISSUE TITLE
Extract Features from Weather Data

### ISSUE THREAD

**Issue by eclee25** [jasonasher/dc_doh_hackathon#21]
Start with the Weather data in the `/Data Sets/Weather at National Airport/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

Write a script that uses this data to produce a feature data table for each of the following weather variables -- total precipitation, average temperature, average maximum temperature, and average minimum temperature -- aggregated by week at the weather station at National Airport.

You can find the data format and examples on the `Feature Dataset Format` tab in [this document](https://docs.google.com/spreadsheets/d/1dp82BlwxMHGIiNPjfspWBkp_K1SZox0PXug8J8aOssU/edit#gid=1961157256)

Check out the README file for additional information on the units for each variable.

**Input:**
CSV files with data for each given year

**Output:**
A CSV file with

-1 row for each feature id, week, year, and census block
-The dataset should include the following columns:

`feature_id`: The ID for the feature, in this case, `"weather_total_precipitation"` or `"weather_average_temperature"` or `"weather_average_minimum_temperature"` or `"weather_average_maximum_temperature"`
`feature_type`: Leave blank
`feature_subtype`: Leave blank
`year`: The ISO-8601 year of the feature value
`week`: The ISO-8601 week number of the feature value
`census_block_2010`: Leave blank
`value`: The value of the feature, i.e. the total amount of precipitation accumulated in a given week, or the average daily minimum temperature in a given week

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by jasonasher** [comment]
Closed by PR #52
