### ISSUE TITLE
Extract Features from Population Data

### ISSUE THREAD

**Issue by eclee25** [jasonasher/dc_doh_hackathon#22]
Start with the Population data in the `/Data Sets/Population by Census Block/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

Write a script that cleans and aggregates this data to produce feature data tables for population at the census block, ANC, and ward levels.

For reference, you can read about the `GEOID` field [here](https://www.census.gov/geo/reference/geoidentifiers.html).

You can find examples on the `Feature Dataset Format` tab in [this document](https://docs.google.com/spreadsheets/d/1dp82BlwxMHGIiNPjfspWBkp_K1SZox0PXug8J8aOssU/edit#gid=1961157256)

Note that this issue depends upon the spatial crosswalk from **Issue #23**

**Input:**
CSV files with data for each given year and spatial scale (census block, ANC, and ward)

**Output:**
A CSV file with

-1 row for each feature id, year, and spatial unit
-The census block dataset should include the following columns:

`feature_id`: The ID for the feature, in this case, `"population"`
`feature_type`: Leave blank
`feature_subtype`: Leave blank
`year`: The ISO-8601 year of the feature value
`week`: Leave blank
`census_block_2010`: The 2010 Census Block of the feature value
`value`: The value of the feature, i.e. population

- For the ANC and ward datasets, replace the `census_block_2010` column with `anc_2013` or `ward_2012`

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by catalinalupu** [comment]
Completed - Uploaded to Dropbox by Tim Martin.
