### ISSUE TITLE
Create a spatial crosswalk for Census Tract & Block, ANC, and Ward

### ISSUE THREAD

**Issue by eclee25** [jasonasher/dc_doh_hackathon#23]
Start with the geocoded 311 Service request data (dc_311-2016.csv) in the `/Data Sets/Shapefiles and Geospatial Information/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).

1. Write a script to extract the unique ward, ANC, Census tract and block information into a spatial crosswalk. 
2. Verify that all census blocks in DC are represented in the dataset by comparing it to all of the unique census block IDs in the Population by Census Block data (`/Data Sets/Population by Census Block/') If there are missing census blocks, brainstorm and implement ways to add the ward and ANC information to the crosswalk.

**Input:**
Geocoded 2016 311 service request data

**Output:**
A CSV file with

- 1 row for each FIPS15
- The following columns:

`fips15`: The 15-digit FIPS code
`census_tract`: The Census Tract number
`census_block`: The Census Block number in the record
`ward_2010`: The 2010 Ward number
`anc_2010`: The 2010 ANC code

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by jasonasher** [comment]
Checked at hacknight.
