### ISSUE TITLE
Extract Features from Building Permit Data

### ISSUE THREAD

**Issue by jasonasher** [jasonasher/dc_doh_hackathon#3]
Start with the Building Permit data in the `/Data Sets/Building Permits/` folder in [Dropbox](https://www.dropbox.com/sh/a1ucls1dwytc22k/AAAd4WCuGdtm6qy3dKyoQRsoa?dl=0).
Write a script that uses this data to produce a feature data table for the number of new building permits issued in the last 4 weeks.

You can find the data format and examples on the `Feature Dataset Format` tab in [this document](https://docs.google.com/spreadsheets/d/1dp82BlwxMHGIiNPjfspWBkp_K1SZox0PXug8J8aOssU/edit#gid=1961157256)

**Input:**
CSV files with data for each given year

**Output:**
A CSV file with

- 1 row for each building permit type and subtype, and each week, year, and census block
- The dataset should include the following columns:

`feature_id`: The ID for the feature, in this case, `"building_permits_issued_last_4_weeks"`
`feature_type`: Building permit type
`feature_subtype`: Building permit subtype
`year`: The ISO-8601 year of the feature value
`week`: The ISO-8601 week number of the feature value
`census_block_2010`: The 2010 Census Block of the feature value
`value`: The value of the feature, i.e. the number of new building permits of the specified types and subtypes issued in the given census block during the previous 4 weeks starting from the year and week above.

**When you are finished**
Submit a pull request on GitHub (or upload your scripts)
Upload any files to [Dropbox](https://www.dropbox.com/request/IB3ojKhcjy29esowKXPX)

**Need more information?**
Flag Jason or Elizabeth, or ask your question in the comments below and we'll respond as soon as we can!

**Comment by courtneycl** [comment]
This one is in progress

**Comment by courtneycl** [comment]
script submitted via PR and dropbox, resulting csv uploaded to dropbox

**Comment by courtneycl** [comment]
@jasonasher I re-uploaded files to dropbox - I forgot `feature_id` on the first files.

**Comment by jasonasher** [comment]
Closed by PR #50
