### ISSUE TITLE
Restaurant inspection data needs remapping. Violation number does not consistently point to same compliance string.

### ISSUE THREAD

**Issue by amitnagis** [jasonasher/dc_doh_hackathon#36]
For e.g. inspection id 897854 and 2646 maps 'Insects, rodents, & animals not present' to violation numbers 26 and 38 respectively.

**Comment by jasonasher** [comment]
This is solved by my recent commit 'Add violation description' to [dc_restaurant_inspections](https://github.com/jasonasher/dc_restaurant_inspections).
